.build-and-push:
  variables:
    NODE_ENV: "production"
    IMAGE: ${CI_REGISTRY}/${NAMESPACE}/${CI_PROJECT_NAME}
    PREFIX: ""
    TAG: $CI_COMMIT_SHORT_SHA
    CI_REGISTRY_CREDS: $CI_REGISTRY_CREDS
    TARGET: "null"
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  interruptible: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_REF_SLUG == $CI_DEFAULT_BRANCH
      when: always
    - when: never
  script:
    - echo "$CI_REGISTRY_CREDS" > /kaniko/.docker/config.json
    - if [ "$TARGET" != "null" ]; then /kaniko/executor --target $TARGET --context $CI_PROJECT_DIR/$PREFIX --destination $IMAGE/$PREFIX:$TAG-$TARGET; fi;
    - if [ "$TARGET" = "null" ]; then /kaniko/executor --context $CI_PROJECT_DIR/$PREFIX --destination $IMAGE/$PREFIX:$TAG; fi;

.hold-release-image:
  variables:
    NODE_ENV: "production"
    IMAGE: ${CI_REGISTRY}/${NAMESPACE}/${CI_PROJECT_NAME}
    TAG: $CI_COMMIT_SHORT_SHA
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  image:
    name: docker:20.10.16
  interruptible: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG
      when: always
    - when: never
  services:
    - docker:20.10.16-dind
  before_script:
    - mkdir -p $HOME/.docker
    - echo $CI_REGISTRY_CREDS > $HOME/.docker/config.json
  script:
    - docker pull ${CI_REGISTRY}/${NAMESPACE}/${CI_PROJECT_NAME}/${PREFIX}:${TAG}
    - docker tag ${CI_REGISTRY}/${NAMESPACE}/${CI_PROJECT_NAME}/${PREFIX}:${TAG} ${CI_REGISTRY}/${NAMESPACE}/${CI_PROJECT_NAME}/${PREFIX}:release
    - docker push ${CI_REGISTRY}/${NAMESPACE}/${CI_PROJECT_NAME}/${PREFIX}:release
