{{- if .Values.ingress.enabled -}}
{{- $mode := .Values.mode }}
{{- $commit := include "wvproduction.commit" . }}
{{- $fullName := include "wvproduction.fullname" . -}}
{{- $chartVersion := $.Chart.Version | replace "+" "_" }}
{{- $ := . -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $fullName }}
    chart: "{{ $fullName }}-{{ $chartVersion }}"
    commit: {{ $commit | quote }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    {{- if .Values.ingress.eksEnabled }}
    kubernetes.io/ingress.class: "marketing-prod"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    {{- end }}
spec:
  {{- if .Values.ingress.https }}
  tls:
  {{- range $key,$val := .Values.ingress.domains }}
  {{- if eq .mode $mode }}
    - hosts:
      {{- range $key,$val := .hosts }}
        - {{ template "wvproduction.hostname" $val }}
      {{- end }}
      secretName: {{ $fullName }}-tls-secret-{{ $key }}
  {{- end }}
  {{- end }}
  {{- end }}
  rules:
  {{- range $domainKey,$domainVal := .Values.ingress.domains }}
    {{- if eq .mode $mode }}
    {{- $alias := .alias }}
    {{- $port := .port }}
    {{- range $key,$val := .hosts }}
    {{- if lt $key 1 }}
    - host: {{ template "wvproduction.hostname" $val }}
      http: &host-config-{{ $domainKey }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-{{ $alias }}-service
                port:
                  number: {{ $port }}
    {{- else }}
    - host: {{ template "wvproduction.hostname" $val }}
      http: *host-config-{{ $domainKey }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end -}}
